### ISSUE TITLE
Handle exceeding API rate limit

### ISSUE THREAD

**Issue by hugovk** [nedbat/watchgha#2]
If you've exceeded the rate limit you get something like this:

```console
$ git runs
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/watch_gha_runs", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/watchgha/watch_runs.py", line 94, in main
    doit()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/watchgha/watch_runs.py", line 90, in doit
    done = draw_runs(url)
           ^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/watchgha/watch_runs.py", line 108, in draw_runs
    runs = runs["workflow_runs"]
           ~~~~^^^^^^^^^^^^^^^^^
KeyError: 'workflow_runs'
```

Printing that `runs`:

```python
def draw_runs(url):
    runs = get_json(url)
    print(runs)
```

Gives:

`{'message': "API rate limit exceeded for <snipped IP address>. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)", 'documentation_url': 'https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting'}`

And:

```python
    def get_json(self, url):
        resp = requests.get(url)
        print(resp.status_code)
```

Gives:

```
403
```

There should be some sort of handing here. At least show some sort of error, perhaps give a way to authenticate as well?

**Comment by nedbat** [comment]
I've made a change so you'll see the requests error at least.  My head is spinning with all the authentication possibilities.  Any preferences?

**Comment by hugovk** [comment]
The simplest is probably to look for an env var?

**Comment by nedbat** [comment]
`GITHUB_TOKEN` is now supported as of commit 1fdffb22278c044653ae1c8607cb4aea1db4a072.

**Comment by hugovk** [comment]
Thanks, working now!
